name: Auto-merge for Solo Developer

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  auto-merge:
    name: Auto-merge PR
    runs-on: ubuntu-latest
    if: github.actor == 'g-abate' && github.event.pull_request.draft == false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Wait for all checks to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'TDD Process Validation'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Wait for test coverage
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Test Coverage Validation'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Wait for code quality checks
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Code Quality Checks'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Enable auto-merge
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🤖 **Auto-merge enabled!** 
          
          All required checks have passed:
          - ✅ TDD Process Validation
          - ✅ Test Coverage Validation  
          - ✅ Code Quality Checks
          
          This PR will be automatically merged and the branch will be deleted."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
